name: Tchap
attributes:
  ORGANIZATIONNAME: DINSIC
  
options:
  deploymentTarget:
    iOS: "11.0"
    watchOS: '4.0'
    tvOS: "11.0"
    macOS: "10.15"

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - CHANGES.md
    - AUTHORS.rst
    - Podfile
    - project.yml
    - changelog.d

configFiles:
  Debug: Config/Project-Debug.xcconfig
  Release: Config/Project-Release.xcconfig

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh
    
include:
  - path: Tchap/target.yml
  - path: RiotShareExtension/target.yml
  - path: RiotNSE/target.yml
  - path: TchapTests/target.yml
  - path: DesignKit/target.yml
  - path: RiotSwiftUI/target.yml
  - path: RiotSwiftUI/targetUnitTests.yml
  - path: RiotSwiftUI/targetUITests.yml
  - path: CommonKit/target.yml
  - path: CommonKit/targetUnitTests.yml
  # Disabled due to crypto corruption issues.
  # https://github.com/element-hq/element-ios/issues/7618
  # - path: RiotShareExtension/target.yml
  # - path: SiriIntents/target.yml

packages:
  AnalyticsEvents:
    url: https://github.com/matrix-org/matrix-analytics-events
    exactVersion: 0.23.1
#    path: ../matrix-analytics-events
  Mapbox:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    minVersion: 5.12.2
    maxVersion: 5.13.0
  OrderedCollections:
    url: https://github.com/apple/swift-collections
    minVersion: 1.0.2
    maxVersion: 2.0.0
  SwiftOGG:
    url: https://github.com/element-hq/swift-ogg
    branch: 0.0.1
  WysiwygComposer:
    url: https://github.com/element-hq/matrix-rich-text-editor-swift
    exactVersion: 2.37.12
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit
    majorVersion: 4.7.0
  DTCoreText:
    url: https://github.com/Cocoanetics/DTCoreText
    version: 1.6.26
  PostHog:
    url: https://github.com/PostHog/posthog-ios
    minorVersion: 3.2.5
